### ISSUE TITLE
using selenium 3

### ISSUE THREAD

**Issue by tremkonzah** [ModusCreateOrg/protractorStarterApp#1]
How to use with selenium 3 release?

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
