### ISSUE TITLE
PerformanceTest1.jmx 0kb

### ISSUE THREAD

**Issue by tremkonzah** [ModusCreateOrg/protractorStarterApp#2]
PerformanceTest1.jmx file size 0kb, not able to open this file

**Comment by emimuresan** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
